assists/baremetal_bspconfig_xlnx.py
assists/baremetal_xparameters_xlnx.py
assists/baremetalconfig_xlnx.py
assists/baremetaldrvlist_xlnx.py
assists/baremetallinker_xlnx.py
assists/bmcmake_metadata_xlnx.py

1) Added assist file for generating baremetal board support package config
2) Added assist file for generating xparameters.h file
3) Renamed the linker assist file
4) Generate the required conf files for yocto tool

New Xilinx Baremetal Assists file and Bug fixes and Improvements 

---

assists/baremetal_xparameters_xlnx.py
assists/baremetalconfig_xlnx.py
assists/baremetaldrvlist_xlnx.py
assists/baremetallinker_xlnx.py

Hi @zeddii ,
This patch series does the below
1) Added support for handling clocks and ranges property as per Baremetal requirements 
2) Updated the memory handling based on the CPU cluster address-map property
3) Added support for generating CCI define
4) Added support for memory tests app configuration.
Please review the changes when you have some time.
Regards,
Kedar.

Xilinx Baremetal Assists Feature Enhancments

---

assists/baremetal_bspconfig_xlnx.py
assists/baremetal_xparameters_xlnx.py
assists/baremetalconfig_xlnx.py
assists/baremetaldrvlist_xlnx.py
assists/baremetallinker_xlnx.py
assists/bmcmake_metadata_xlnx.py

Hi,
This pull request does the below 
1) Updates all the assist device-tree node handling based on the cpu cluster address-map property
2) Add support for the versal corter5 machine.
@zeddii  When you have some time please review the pull request and let me know the review comments  
Regards,
Kedar.

Xilinx Baremetal flow assist updates

---

lops/lop-a72-imux.dts
lops/lop-domain-a72.dts
lops/lop-r5-imux.dts

Hi,
1) Adds lops file for A72 domain 
2) Adds lops files for imux to A72 and R5 GIC node replacement 
@zeddii : please review the changes when you have some time
Regards,
Kedar.

lops files for xilinx versal soc

---

assists/cdo.py

remove extra verbose print for now in CDO documentation

---

assists/baremetalconfig_xlnx.py
assists/bmcmake_metadata_xlnx.py

Hi,
This pull request fixes race conditions in the baremetal assist files.
@zeddii , When you have some time please review the changes...
Regards,
Kedar.

Baremetal assist bug fixes

---

assists/baremetalconfig_xlnx.py
assists/baremetallinker_xlnx.py
assists/bmcmake_metadata_xlnx.py

1) Include address-map mapped nodes as well for subsystem configuration
2) Pull driver example only if phandle property is present
3) Update linker assist to point default linker to lower DDR
@zeddii : When you have some time please review the changes...
Regards,
Kedar.

baremetal assist updates

---

assists/cdo.py
assists/subsystem.py
lops/lop-xlate-yaml.dts

- yaml -> dts now matches spec
- update cdo plugin to use latest generated SDT per YAML expansion

Update cdo parsing

---

specification/bus-firewalls.md
specification/domains-yaml.md
specification/remoteproc.md
specification/simplified-yaml.md
specification/specification.md
specification/system-device-tree.dts

Full update on access flags, including their hierarchical definition.
Introduced Simplified YAML and some further domain-specific YAML simplifications.

Specification update

---

assists/openamp-xlnx.py

Use SDT IPI info for IPI information in mailbox xlnx,ipi and interrupts
properties

open-amp: xilinx: update kernel demo ipi assignment

---

assists/openamp-xlnx.py
lops/lop-domain-a72.dts

update openamp versal use cases on top of latest lopper + SDT

Update openamp versal

---

assists/openamp-xlnx.py
lops/lop-domain-a53.dts

support for generating firmware and linux-bootable device tree for OpenAMP on ZU+ for kernel-remoteproc case

Zu support for openamp

---

assists/openamp-xlnx.py

openamp: xilinx: update zu+ mailbox 'reg' property value

---

lopper/assists/xlnx/cdogen.py
lopper/assists/xlnx/ftb.py
lopper/assists/xlnx/protections.py
lopper/assists/xlnx/subsystem.py
lopper/lops/lop-load.dts

add back CDO plugin as the required dependencies have been ported

Add back cdo plugin

---

specification/remoteproc.md

Here make sure label-references are present and all peripherals and
memory are valid and clear.

spec: update remoteproc example per latest spec

---

lopper/assists/petalinuxconfig_xlnx.py

Petalinux tool required additional meta-data about all the IP's
mapped to particular machine, This commit adds support for the same.

lopper: assists: petalinuxconfig_xlnx: Add support for additional meta-data

---

lopper/assists/petalinuxconfig_xlnx.py

This commit updates the indentation and width as per tool
requirments.

lopper: assists: petalinuxconfig_xlnx: Fix indentation and width params

---

lopper/assists/baremetal_xparameters_xlnx.py
lopper/assists/baremetalconfig_xlnx.py

This pull request fixes the race condition (KeyError) in the baremetal assist files...

Fix race condition in the baremetal assist files

---

lopper/assists/openamp_xlnx.py

Currently per spec, the following is valid YAML:
openamp_r5_0_cluster:
compatible: openamp,domain-v1
cpus:
- cluster: cpus_r5
cpumask: 0x1
mode:
secure: true
....
openamp_r5_1_cluster:
compatible: openamp,domain-v1
cpus:
- cluster: cpus_r5
cpumask: 0x2
mode:
secure: true
Where the cpumask denotes as follows:
- 0x0 is lockstep
- 0x1 is rpu0
- 0x2 is rpu1
Ensure that OpenAMP plugin handles this properly.

openamp: Update YAML handling to match spec

---

lopper/lops/lop-domain-linux-a53-prune.dts
lopper/lops/lop-domain-linux-a53.dts

Hi,
amba_pl node needs to be preserved in the final linux dtb/dts inorder to test the PL driver this pull request does the same.
CC: @zeddii 
Regards,
Kedar.

ZynqMP linux PL boot issues

---

lopper/assists/bmcmake_metadata_xlnx.py

To compile a driver example all the required fields/conditions mentioned
in the driver example section must be met, update the logic for the same.

lopper: assists: bmcmake_metadata_xlnx: Fix race condition in the code

---

lopper/assists/petalinuxconfig_xlnx.py

commit 'ac1b41946b11' Update the command line arguments update the assist for the same.

lopper: assists: petalinuxconfig_xlnx: Update assist as per latest lopper changes

---

demos/openamp/README.md

Markdown format required for OpenAMP doc generation.
Signed-off-by: Tammy Leino <tammy_leino@mentor.com>

Convert demo readme to markdown

---

lopper/assists/baremetal_xparameters_xlnx.py
lopper/assists/baremetalconfig_xlnx.py
lopper/assists/baremetaldrvlist_xlnx.py
lopper/assists/bmcmake_metadata_xlnx.py

Revert the CMakeLists.txt file generation as it should be taken care by the scripts in the non yocto flow
Update hw meta generation for standalone bsp as per review comments (Generate node label name in cmake meta-data rather than node name)
Regards,
Kedar.

baremetal assists bug fixes..

---

lopper/assists/bmcmake_metadata_xlnx.py
lopper/assists/petalinuxconfig_xlnx.py

1. Add support for device_id meta-data generation in petalinux_config assist file
2. Add support for hardware ip name cmake meta-data generation if present in the system device-tree.

Enhancements in the assists

---

lopper/assists/generate_config_object.py

lopper: assists: generate_config_object: Add outdir option support

---

lopper/assists/baremetaldrvlist_xlnx.py
lopper/assists/baremetallinker_xlnx.py

1) Add default memory section for cortexr5 processor
2) Generate both xlnx,ip-name and xlnx,name variable meta-data in the ip_drv_map.yaml file

baremetal assist enhancments

---

lopper/assists/openamp.py
lopper/assists/openamp_xlnx.py
lopper/assists/openamp_xlnx_common.py

Update Xilinx OpenAMP Plugin:
- use as module 
- pass role (host/remote)
- output stripped down header file with channel info
- remove dead code

Openamp update jun22 2023

---

lopper/assists/baremetal_gentestapp_xlnx.py

Currently we are reading the tapp schema for all the driver yamls in a given repo and generating header meta-data in testperiph.c file irrespective of the driver mapped or not in a given system device-tree, This commit fixes this issue.

lopper: assists: baremetal_gentestapp_xlnx: Don't generate meta-data for the non mapped drivers

---

lopper/assists/baremetalconfig_xlnx.py

Drivers such as rfdc and the dfe drivers have nested structures which are not repeated.
SD_FEC has device tree paramaters that are an array.
This patch will allow handling for these kinds of drivers

assists/baremetal: Add handling for non homogeneous driver device trees V2

---

lopper/assists/baremetalconfig_xlnx.py
lopper/assists/bmcmake_metadata_xlnx.py

lopper: assists: bug fixes in the assists 

---

lopper/assists/baremetal_gentestapp_xlnx.py
lopper/assists/baremetal_xparameters_xlnx.py
lopper/assists/baremetallinker_xlnx.py
lopper/assists/bmcmake_metadata_xlnx.py

1) Handle string property values in xparameters assist
2) Fix race condition in the self test app declartion
3) Add missing tcm memory section for versal a72 and r5 processors

lopper bug fixes in assits

---

lopper/assists/baremetallinker_xlnx.py

Update the assist to support ps7_ram.

lopper: assists: baremetallinker_xlnx: Add support for ps7_ram

---

lopper/assists/baremetal_xparameters_xlnx.py
lopper/assists/bmcmake_metadata_xlnx.py

Generate BOARD define as XPS_BOARD instead of XPAR_BOARD.

lopper: assists: Generate BOARD define inline with existing code

---

lopper/assists/openamp_xlnx.py
lopper/assists/openamp_xlnx_common.py

Add values specific for host to generated header file

openamp: xlnx: Add Host specific values

---

lopper/assists/baremetal_xparameters_xlnx.py
lopper/assists/baremetalconfig_xlnx.py

This is an extension to the previous Pull Request: https://github.com/devicetree-org/lopper/pull/218

64 bit property support in xparameters.h

---

lopper/assists/baremetal_xparameters_xlnx.py
lopper/assists/baremetallinker_xlnx.py

Few Bug fixes in baremetal_xparameters and baremetal_linker assist files.

lopper:assists Bug fixes in baremetal_xparameters and baremetal_linker assist files.

---

lopper/assists/baremetal_xparameters_xlnx.py

These changes are requested/needed based on latest discussions with Video and PM Apps team.

Changes in canonical entries of xparameters

---

lopper/assists/openamp_xlnx.py

update output file string values

Openamp xlnx outputfile formatting

---

lopper/assists/openamp_xlnx.py

Enable usage of module using explicit key value pairs as command line arguments
The arguments required now are:
--openamp_role=[host|remote]
Must be 'host' or 'remote'. This denotes the role which the output header file will target.
--openamp_host and --openamp_remote
These each must correspond to the relevant cores in a OpenAMP Channel Pair. On ZynqMP if a YAML has A53-0 as host and RPU0 as remote a valid command line set would be:
--openamp_role=host --openamp_host=a53_0 --openamp_remote=r5_0

openamp: xlnx: Add new module flags for role, host and remote

---

lopper/assists/baremetal_xparameters_xlnx.py
lopper/assists/baremetalconfig_xlnx.py
lopper/assists/bmcmake_metadata_xlnx.py

Pull request does the below
1) Add support for XPAR_CPU_ID in cmake meta-data
2) Add support for the Generic Interrupt ID

baremetal assists enhancements 

---

lopper/assists/baremetalconfig_xlnx.py

Update the logic in get_pci_range API to get the correct PCI range in case of 64 Bit PCI bar having higher PCI addresses.

assists:baremetalconfig_xlnx: Update logic to get correct PCI range

---

lopper/assists/baremetal_gentestapp_xlnx.py
lopper/assists/domain_access.py
lopper/assists/gen_domain_dts.py
lopper/lops/lop-a53-imux.dts
lopper/lops/lop-a72-imux.dts
lopper/lops/lop-a78-imux.dts

This pull request updates the gen_domain_dts assist to generate linux device-tree

Updated the gen_domain_dts assist to generate the linux device-tree

---

lopper/assists/openamp_xlnx.py
lopper/lops/lop-openamp-invoke.dts
lopper/lops/lop-openamp-prune.dts

update lops for openamp use cases

Openamp xlnx lops update

---

lopper/assists/gen_domain_dts.py
lopper/assists/xlnx_overlay_dt.py

--> Make sure update the symbol node entry for GIC node renaming 
--> In overlay make sure to update the interrupt-parent field for PL nodes.

Linux Overlay Improvments

---

lopper/assists/gen_domain_dts.py

Add the missing brackets around the or condition.

lopper: assists: gen_domain_dts: Fix syntax issue in the code

---

lopper/assists/baremetalconfig_xlnx.py
lopper/assists/baremetallinker_xlnx.py

The handling of domains is now done on the Lopper frontend, so remove any code related to domains from the assist files.

lopper: assists: Remove domain specific code from the assist

---

lopper/assists/openamp_xlnx.py

Enable other Versal and ZynqMP SOCs

openamp: xlnx: Add support for more SOC's

---

lopper/assists/openamp_xlnx.py

generalize parsing to account for different substrings in SOC compatible string

openamp: xlnx: Clean up SOC Parsing

---

lopper/assists/gen_domain_dts.py
lopper/assists/xlnx,rfdc.yaml
lopper/assists/xlnx,sd-fec.yaml

1. Refactor to allow special handling for multiple IPs
2. Child node handling: If a child node does not have any of of the properties listed in the YAML (or a child with any of these properties), it will be removed from the device tree.
3. Add YAML for RFDC (second special handling)

lopper: assists: Enhance special property removal

---

lopper/assists/openamp_xlnx.py

Enable TCM to be pulled in from domain and not YAML

Openamp xlnx yaml tcms

---

lopper/assists/gen_domain_dts.py
lopper/assists/openamp_xlnx.py

tested builds for latest vhk158 and zcu102 SDT in workflow.

Openamp xlnx cleanup feb23

---

lopper/assists/baremetal_validate_comp_xlnx.py
lopper/assists/baremetal_xparameters_xlnx.py
lopper/assists/baremetalconfig_xlnx.py
lopper/assists/bmcmake_metadata_xlnx.py
lopper/assists/gen_domain_dts.py
lopper/assists/xlnx,xdma-host.yaml

Pull request does the below
1. preserve the device-tree node order while generating baremetal meta data
2. Add assist to validate the hardware required for a given ESW component

Baremetal Enhanments

---

lopper/assists/openamp_xlnx.py

Tested lopper-runs for VNET, Versal and ZynqMP with this

Openamp versalnet compat str

---

lopper/assists/openamp_xlnx.py

please merge this 1 commit to both master and 2024.x branch @zeddii

openamp: xlnx: versal: match model parsing same as VNET

---

lopper/assists/openamp_xlnx.py

openamp: xlnx: Add vc-p and vn-p models

---

lopper/assists/baremetal_xparameters_xlnx.py

Current implementation doesnt generate canonical definitions for IPI targets.
Generate Canonical definitions of IPI Bitmask and Buffer Index for the available IPI targets.
@onkarharsh @kedareswararao can you please review ?

assists: baremetal_xparameters: Generate Canonical definitions for IPI targets

---

lopper/assists/baremetallinker_xlnx.py
lopper/assists/openamp_xlnx.py

This patch does 2 things:
1. Validate RPMsg carveouts to ensure they are present for host and remote OpenAMP Domains
2. Once carveouts are validated, enable the DDR OpenAMP carveout for ELF Load to propagate to generated linker. Here this means that if linker module has 'openamp' set then attempt to get relevant OpenAMP DDR node's base and length which will be used in linker-metadata.

openamp: Add Validation for carveouts and linker

---

lopper/assists/xlnx_overlay_dt.py

It adds initial zynq pl configuration support for full bitstream use cases.

lopper: assists: Initial support for zynq pl configuration

---

lopper/assists/yaml_bindings/xlnx,v-hdmi-rxss1.yaml
lopper/assists/yaml_bindings/xlnx,v-hdmi-txss1.yaml

Add HDMI 2.1 Rx Subsystem DT yaml to yaml_bindings

lopper: assists: gen_domain_dts: Add HDMI 2.1 Rx Subsystem DT yaml

---

lopper/assists/yaml_bindings/xlnx,dp-tx.yaml
lopper/assists/yaml_bindings/xlnx,v-dprxss.yaml
lopper/assists/yaml_bindings/xlnx,vphy.yaml

Add DP1.4 Rx Subsystem DT yaml to yaml_bindings
Add DP1.4 Tx Subsystem DT yaml to yaml_bindings
Add phandle to Video Phy Controller DT yaml to yaml_bindings

Add DP1.4 Rx/TX Subsystem DT Yaml bindings

---

lopper/assists/baremetal_gentestapp_xlnx.py

Pull the driver examples mentioned in the tapp section of driver.yaml based on the hwproperties mentioned.
@onkarharsh @kedareswararao Can you please review this PR ?

assists: baremetal_gentestapp: Pull the examples based on the hwproperties

---

lopper/assists/xlnx_overlay_dt.py

It adds initial support for Versal Gen2 pl configuration use cases.

lopper: assists: Initial support for Versal Gen2 pl configuration

---

lopper/assists/gen_domain_dts.py

Yocto project expects zynq DDR base addresses to start from 0x0 for linux to boot. This has been a legacy expectation which is logically flawed but working. Add the temporary workaround to unblock them until the QEMU issue and the yocto integration issues are resolved.

assists: gen_domain_dts: Hardcode DDR address for Zynq to always start from 0

---

lopper/assists/gen_domain_dts.py

Add support to generate zephyr compatible device
tree. User needs to pass argument "zephyr_dt" for
generating zephyr device tree and Kconfigs which
are dependent on HW design.
zephyr_dt option does following operations,
- Change name of amba_pl node to soc, and take care of all references to amba_pl.
- Update chosen node with properties needed by zephyr. Zephyr executable would use memory node pointed zephyr,sram property. Hence, find out memory node with largest size and assign it to zephyr,sram.
- Read cflags.yaml and generate riscv,isa property for MB-V CPU
- Generates Kconfig.soc and Kconfig.defconfig

assists: gen_domain_dts: Add support for MB-V zephyr

---

lopper/assists/yaml_bindings/xlnx,audio-formatter.yaml
lopper/assists/yaml_bindings/xlnx,i2s.yaml
lopper/assists/yaml_bindings/xlnx,sdi-tx.yaml
lopper/assists/yaml_bindings/xlnx,sdirxss.yaml
lopper/assists/yaml_bindings/xlnx,spdif.yaml

Add DT yaml files for SDI subsystems Tx & Rx and Audio Ip's - I2S, SPDIF & Audio formatter.

Add DT yaml files for SDI Tx & Rx and Audio IP's

---

lopper/assists/openamp_xlnx.py

Validate reserved-mem regions do not overlap

openamp: xlnx: Validate reserved-mem regions

---

lopper/assists/openamp_xlnx.py

ensure names are compliant with DT convention. Should be 'name@Addr'.

openamp: xlnx: rpmsg-native: update node names for shared mem and IPI

---

lopper/assists/baremetal_gentestapp_xlnx.py

Add logic to include appropriate interrupt header files for DMA and MCDMA.

lopper: assists: baremetal_gentestapp_xlnx: Add support for dma headers

---

lopper/assists/baremetal_gentestapp_xlnx.py

Add a condition to check 'tapp' section present in axiethernet yaml processing.

lopper: assists: baremetal_gentestapp_xlnx:Add condition for tapp section check

---

lopper/assists/yaml_bindings/xlnx,vphy.yaml

Added FMC connector property to load on board fmc driver modules.

lopper: vphy: Add FMC connector property

---

lopper/assists/baremetallinker_xlnx.py
lopper/assists/gen_domain_dts.py

Pull request does the below
--> lopper: assists: baremetallinker_xlnx: Add support for handling xlnx, memory-ip-list property
--> assists: gen_domain: linker: Update the assist to handle ZU+ fsbl usecase
--> assists: baremetalinker: Update microblaze-v default address

lopper updates

---

lopper/assists/yaml_bindings/xlnx,v-hdmi-rxss1.yaml
lopper/assists/yaml_bindings/xlnx,v-hdmi-tx-ss.yaml
lopper/assists/yaml_bindings/xlnx,v-hdmi-txss1.yaml

Add the snd-pcm properties for the hdmi systems.

lopper: assits: yaml_bindings: Add audio snd-pcm proerties

---

demos/openamp/README.md
demos/openamp/inputs/openamp-overlay-zynqmp-dev-mem.yaml

Fix README.md file lopper demo as per 2024.2 latest lopper release. Introduce new yaml in inputs directory again for demo purpose.

demo: openamp: Make openamp demo work

---

demos/openamp/inputs/openamp-overlay-zynqmp.yaml
lopper/assists/openamp.py
lopper/assists/openamp_xlnx.py
lopper/lops/lop-xlate-yaml.dts

@zeddii  please wait on merge
@tnmysh  please take a look
this PR
1. preserve backward compatibility
2. enable new driver -- tested in build and boot with latest zynqmp BSP and openamp demo on target 
thanks

Openamp xlnx assist update oct29 2025

---

lopper/assists/baremetal_xparameters_xlnx.py
lopper/assists/baremetalconfig_xlnx.py
lopper/assists/common_utils.py
lopper/assists/gen_domain_dts.py

lopper: assists: baremetalconfig_xlnx: For scan_reg_size added exception to handle the Index error and added logger warnings
lopper: assists: baremetal_xparameters_xlnx: Added logger messages and removed duplicate code
lopper: assists: gen_domain_dts: Removed duplicate code

lopper: assists: common_utils: Added logger setup based on verbose

---

lopper/assists/baremetallinker_xlnx.py

Set memtest_config to False when default_ddr is updated based on valid_memips so that the rest of the logic doesnt evaluate default_ddr again for memory test configuration.
Also set a flag valid_memfix to inform rest of the logic to not set ddr_default further as the default mem was already set using valid mem ips. Use the same valid_memfix flag to pop the default_ddr to zeroth location in memory IP lists so that the memory test doesnt list it in memories to be tested.
Acked-by: Anirudha Sarangi <anirudha.sarangi@amd.com>

baremetallinker: set memtest_config to False while updating default_ddr based on valid_mem_ips

---

lopper/assists/baremetal_bspconfig_xlnx.py
lopper/assists/baremetal_getsupported_comp_xlnx.py
lopper/assists/baremetal_validate_comp_xlnx.py
lopper/assists/baremetal_xparameters_xlnx.py
lopper/assists/baremetalconfig_xlnx.py
lopper/assists/bmcmake_metadata_xlnx.py
lopper/assists/common_utils.py

lopper:assists:baremetal_xparameters_xlnx: Fixed new line issue

lopper:assists: Added logging

---

lopper/assists/bmcmake_metadata_xlnx.py

Updated logic to remove unnecessary timer instances in metadata list

lopper: assists: Optimized metadeta generation logic

---

lopper/assists/gen_domain_dts.py
lopper/assists/openamp.py
lopper/assists/openamp_xlnx.py
lopper/assists/openamp_xlnx_common.py

please wait for other review on this PR https://github.com/devicetree-org/lopper/pull/427 first before merging @zeddii

Openamp xlnx freertos in output

---

device-trees/system-device-tree-versal-vck190.dts
lopper_sanity.py

@onkarharsh  @kedareswararao  please review before  merge
CC @zeddii

lopper_sanity: xlnx: Add sanity test for simple gen_domain case

---

lopper/assists/baremetallinker_xlnx.py

Add CODE and DATA sections in the linker to inline with xsct

lopper:assists:baremetallinker_xlnx: Add CODE and DATA sections

---

lopper/assists/gen_domain_dts.py
lopper/assists/zephyr_supported_comp.yaml
lopper/lops/lop-mbv-zephyr-intc.dts

--> Add support for zephyr,shell-uart property generation. --> Remove unused properties from cpu node.

lopper: assists: zephyr: Updates for mbv zephyr

---

lopper/assists/README

- Documented the usage syntax for `xlnx_overlay_dt.py`.
- Added usage details and example commands.
- Improved clarity and usability for FPGA configuration workflows.

Update README: Add xlnx_overlay_dt.py usage details

---

lopper/assists/yaml_bindings/xlnx,frmbuf-rd-wr.yaml

Add new tile format property to the yaml documentation.

lopper: assists: yaml_bindings: Add tile format property

---

lopper/assists/baremetal_bspconfig_xlnx.py
lopper/assists/baremetal_gentestapp_xlnx.py
lopper/assists/baremetal_getsupported_comp_xlnx.py
lopper/assists/baremetal_validate_comp_xlnx.py
lopper/assists/baremetal_xparameters_xlnx.py
lopper/assists/baremetalconfig_xlnx.py
lopper/assists/baremetaldrvlist_xlnx.py
lopper/assists/baremetallinker_xlnx.py
lopper/assists/bmcmake_metadata_xlnx.py
lopper/assists/common_utils.py

Enhanced logging in Lopper to improve traceability and debugging. Modified relevant scripts to align with the updated logging structure. These changes enhance maintainability without impacting functionality.

lopper: Improved Logging for Better Traceability

---

lopper/assists/gen_domain_dts.py
lopper/assists/zephyr_supported_comp.yaml

Add support to create clock nodes.
Add support to read cpu input clock for r52.

Fix zephyr build failure on r52

---

lopper/assists/README

Updates the README to include details and usage instructions for the new xlnx_overlay_pl_dt.py assist. This update adds a description, usage syntax, argument details, and an example command.
It also includes a note recommending the use of xlnx_overlay_pl_dt.py over the older xlnx_overlay_dt.py due to improved robustness and compatibility.

lopper: update README with xlnx_overlay_pl_dt.py details and usage

---

lopper/assists/openamp_xlnx.py

fixes:
- UART issue
- IPI set up for latest driver

openamp: xlnx: zephyr: fix up for latest

---

lopper/assists/yaml_bindings/xlnx,dsi.yaml
lopper/assists/yaml_bindings/xlnx,sdirxss.yaml

1. xlnx,dsi.yaml : modified to add a new property of linerate
2. xlnx,sdirxss.yaml : modified to add a new property of dynamic bpc.

Yaml changes for connectivity IP's

---

lopper/assists/gen_domain_dts.py

Do mailbox prune and modification xlnx_remove_unsupported_nodes only

lopper: gen_domain_dts: zephyr: consolidate mailbox setup

---

lopper/assists/gen_domain_dts.py

Zephyr's watchdog samples/tests requires watchdog0 alias support. Add watchdog0 alias support for axi-timebase-wdt and wwdt nodes.

gen_domain_dts: Add watchdog0 alias support for Zephyr DT generation
