devicetree-org/lopper

- assists/openamp-xlnx.py
- lops/lop-domain-r5.dts
As the openamp related memory carveouts as described in the input system DT and are output into the openamp specific header file, they should also be available for validation in output DTs. 
output the values to memory-region property in the corresponding R5 mem nodes to further this effort.
> assists: openamp-xlnx.py: output mem carveouts to r5 mem nodes

- assists/baremetal-linker_xlnx.py
- assists/baremetalconfig_xlnx.py
- assists/baremetaldrvlist_xlnx.py
Hi Bruce,
This patch series adds assists for xilinx baremetal use cases
Patch
1/3: Add support for generating the baremetal driver config file.
2/3: Add support for returning valid driver list for provided system dt configuration.
3/3: Add support for the baremetal linker generation.
Please review the changes and let me know your comments.
Regards,
Kedar.
> Xilinx Baremetal driver assist files

- assists/baremetal_gentestapp_xlnx.py
- assists/baremetallinker_xlnx.py
While generating the peripheral test meta-data existing logic
is not properly updating the driver example names in the file_list
text file, When running the assist file multiple times.
This commit fixes the above-mentioned issue.
> assists: baremetal_gentestapp_xlnx: Fix race condition in files_list generation

- assists/baremetal_xparameters_xlnx.py
- assists/baremetalconfig_xlnx.py
When the device-tree node property contains the value in
/bits/ format, Standalone driver expects the property value
which is represented in the last nibble.
This commit updates the logic for the same.
> assists: baremetal*: Handle /bits/ value as properly

- lopper.py
Reduce the mandatory library dependencies for lopper to enable it to run
natively in OpenEmbedded and Yocto build environments for device tree
processing during builds. This retains the ability to run the flask
server when the libraries are available.
Making flask support optional enables lopper to run using only the
python recipes that already support native builds in meta-virtualization
and its layer dependencies.
Signed-off-by: Christopher Clark <christopher.clark@starlab.io>
> lopper: make flask dependency optional to support integration

- assists/baremetalconfig_xlnx.py
While validating the compatible match it should be anyOf supported
compatible list instead of first one.
> assists: baremetalconfig_xlnx: check for anyOf compatible strings

- README
- README-architecture.txt
- assists/subsystem.py
- lops/lop-xlate-yaml.dts
This PR mainly has some pre-requisite changes required for protection plugin and a couple minor fixes for typos and readme.
Summary:
- fixes for typos in xlate-yaml and readme
- xlate-yaml: fix generation of subsystem node names and labels
> xlate-yaml and readme fixes

- assists/xlnx_overlay_dt.py
This patch adds a new assist support with name xlnx_overlay_dt, which generates
an overlay dts file.
This assist expects the following arguments
- A Machine name which is cortexa72-versal or cortexa53-zynqmp
- An optional configuration option, which is full to support full
bit stream designs. The default option is full if no argument is
specified.
- Another optional argument external_fpga, which is used to
apply an overlay with out loading the bit stream. This is needed
for versal full bit stream use cases.
Signed-off-by: Naga Sureshkumar Relli <naga.sureshkumar.relli@xilinx.com>
> Add support for overlay dts generation

- assists/baremetal_xparameters_xlnx.py
- assists/baremetalconfig_xlnx.py
- assists/bmcmake_metadata_xlnx.py
Inorder to support PDT (parsed device-tree) SDT.FDT calls
shouldn't be used in the assist files.
This commit updates the assist for the same.
@zeddii : After this commit still we are using sdt.FDT calls at two places in baremetal assists,
1) sdt.FDT.get_alias (Couldn't able to find equivalent API in lopper tree)
2) Lopper.node_properties_as_dict(sdt.FDT) (This can be resolved need to look into lopper front end..)
> assists: baremetal*: Remove references to sdt.FDT handling

- assists/baremetal_xparameters_xlnx.py
- assists/baremetalconfig_xlnx.py
- assists/baremetallinker_xlnx.py
- lops/lop-domain-a72.dts
- lops/lop-domain-linux-a53.dts
1) Fix sdt.FDT checks in baremetal assist files 
2) Fix race condition in baremetal linker assist for memory test
3) Update A72 domain lops file as per latest system device-tree generated by the device-tree-generator tool 
4) Update A53 linux domain lops file as per latest system device-tree generated by the device-tree-generator tool
> assists: baremetal*: Bug fixes

- lops/lop-domain-a72.dts
as the TCM nodes have changed in generated SDT do not prune now deprecated nodes
> lops: lop-domain-a72: do not prune TCM nodes

- lops/lop-domain-linux-a53.dts
For Linux domain only ddr memory node is valid,
This commit removes the unneeded bram memory nodes from
the system device-tree.
> lops: lop-domain-linux-a53: lops: Remove unneeded bram memory node

- lops/lop-domain-linux-a53.dts
Inorder to delete the axi bram memory node, we need
to select all the memory nodes in a given system device-tree,
Commit dac94bbf8302 missed this logic,
This commit updates the same.
> lops: lop-domain-linux-a53: Select all the memory nodes

- lops/lop-domain-a72.dts
Currently for Versal Linux boot there is issue with multiple nodes of the same
name being created for boot and this causes small kernel crash.
Remove these nodes to fix this issue
> lops: lop-domain-a72: prune certain TCM nodes for Versal Linux boot

- lops/lop-domain-linux-a53.dts
To Inline with the existing flow disable the smmu node
for zynqmp linux domain use case.
> lops: lop-domain-linux-a53: Disable SMMU node

- lops/lop-domain-a72.dts
previously TCM pruning only worked for specific compatible string forms
now check for if the string is a substring and/or if it is part of multiple
compatible strings before deleting to ensure the nodes are removed.
> lops: lop-domain-a72: fix TCM pruning

- assists/xlnx/cdogen.py
- assists/xlnx/protections.py
Due to a few platform specific dependencies at boot, there is a need to open up few protected regions for specific masters. Without this, the boot will not work on the platform. These protected regions are referred to as "RegNodes" (or Register Nodes).
Currently, there is no S-DT/YAML specification available to express protections for RegNodes. Due to this, the output CDO directly needs to be patched with hardcoded entries so the boot will function. These will be removed in later when the gaps in the specification are resolved.
Signed-off-by: Izhar Shaikh <izhar.ameer.shaikh@xilinx.com>
> xlnx: xppu/xmpu: add permitted apertures for boot protections

- specification/bus-firewalls.md
- specification/domains-yaml.md
- specification/os,type.md
- specification/remoteproc.md
- specification/specification.md
- specification/system-device-tree.dts
Remove resource-groups, not shared resources are simply repeated.
Simplify access flags, they are just specified at each level
independently.
Update remoteproc binding.
Introduce implicit default access flags.
Introduce secure-bus and secure-address-map.
Introduce os,type.
Signed-off-by: Stefano Stabellini <stefano.stabellini@xilinx.com>
> spec: remove resource-groups

- lopper/assists/openamp.py
- lopper/assists/openamp_xlnx.py
- lopper/assists/subsystem.py
- lopper/lops/lop-load.dts
- lopper/lops/lop-xlate-yaml.dts
add stubs for OpenAMP YAML expansion as follows
- subsystem: add YAML handler for the domain-to-domain YAML property
- openamp generic: add landing function to determine if RPMsg or Remoteproc relation and which vendor
- openamp xilinx: stub for handling specific to Xilinx
- rename openamp-xlnx to openamp_xlnx for includes
- remove CDO from being loaded as it currently is based off deprecated Lopper code
> Update openamp yaml stubs

- lopper/assists/openamp.py
- lopper/assists/openamp_xlnx.py
- lopper/lops/lop-openamp-versal.dts
Stub to catch processing of OpenAMP Domains is now present.
Additionally, route stub for Xilinx OpenAMP Domains.
> openamp: add stub for OpenAMP Domain processing landing function

- lopper/assists/petalinuxconfig_xlnx.py
Petalinux tool has a software configuration wizard in which it provides
options for configuring ethernet, memory, serial device etc...
To provide required hardware information, this commit adds an assist file
which reads the meta-data file(yaml file provided by petalinux tool) and
system device-tree and outputs a JSON file which will be consumed by the
petalinux tool to populate hardware information in the software
configuration wizard.
> lopper: assists: petalinuxconfig_xlnx: Add assist file for generating petalinux tool required configuration

- lopper/assists/baremetallinker_xlnx.py
In the system device tree, there will be a per CPU cluster address-map
property, As per the system device-tree specification  the start address
in the address-map need not to be mapped with the node start address
(ex: for entire system memory node has 2 GB out of which r5 can be
mapped to only 1GB memory), Existing assist logic is not considering
this use case this patch fixes this issue.
> lopper: assists: breametallinker: fix race condition in memory node handling

- lopper/assists/openamp_xlnx.py
As input system device tree has updated, make sure plugin
uses latest properties and alignment.
> openamp: xlnx: Update RPMsg-kernel mailbox information

- lopper/lops/lop-domain-linux-a53-prune.dts
Remove all the uneeded nodes when generating the linux dtb/dts.
CC: @zeddii, @BenLevinsky
> lopper: lops: lop-domain-linux-a53-prune: Remove unneeded nodes for Linux boot

- lopper/assists/bmcmake_metadata_xlnx.py
When the driver required propery is missing in the device-tree node
match_list should be initialized to false, currently it is empty
this commit fixes this issue.
> lopper: assists: bmcmake_metadata_xlnx: Fix race condition in the assist file

- lopper/assists/baremetallinker_xlnx.py
While handling memory domain nodes domain start address can be
at any offset in the memory node range, existing logic is not
properly handling if the address is random address, this commit
fixes this issue.
> lopper: assists: baremetallinker_xlnx: Fix race condition in memory domain handling

- lopper/lops/lop-domain-linux-a53.dts
In ZynqMP system device-tree tcm_ram mapped into global
tcm ram node and individual atcm and btcm global nodes,
this commit deletes the duplicate psu_r5_tcm_ram_global
from the linux device-tree.
> lopper: lops: lop-domain-linux-a53: Remove duplicate psu_r5_tcm_ram_global node

- lopper/assists/extract-xen.py
Currently extract assist only adds "simple-bus" but we also need to copy
all the other compatibles from the sdt root node. This is because some
drivers may refuse to continue unless they find the root-level board
compatible property.
Signed-off-by: Michal Orzel <michal.orzel@amd.com>
> extract-xen: Copy sdt root compatibles into extracted node

- lopper/assists/baremetal_bspconfig_xlnx.py
- lopper/assists/baremetal_getsupported_comp_xlnx.py
- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/baremetalconfig_xlnx.py
- lopper/assists/baremetaldrvlist_xlnx.py
- lopper/assists/baremetallinker_xlnx.py
- lopper/assists/bmcmake_metadata_xlnx.py
- lopper/lops/lop-cpulist.dts
1) Add support for outdir option in assists 
2) Added new assist for getting the supported apps and libs list for supported os along with it's description 
3) Added new lops file getting cpu names for a given system device-tree
4) Updated the assists to remove hard coded cpu compatible to yocto machine dictionary and fixed assists to take cpu name as input instead of yocto machine name.
> lopper: assits: Improvements in baremetal assists

- lopper/assists/baremetal_gentestapp_xlnx.py
- lopper/assists/baremetal_getsupported_comp_xlnx.py
- lopper/assists/baremetalconfig_xlnx.py
- lopper/assists/baremetaldrvlist_xlnx.py
- lopper/assists/bmcmake_metadata_xlnx.py
After last updates in assists, there were still few places left where outdir option was not being used. This patch adds outdir support at the remaining places. In addition it adds support to use the changed yaml format in embeddedsw.
Signed-off-by: Onkar Harsh <onkar.harsh@amd.com>
> lopper:assists: Update assists to support outdir option and the changed yaml format in embeddedsw

- lopper/assists/petalinuxconfig_xlnx.py
Processor name should be passed by user, update the assist for the same.
> lopper: assists: petalinuxconfig_xlnx: Remove the hardcoded processor name

- lopper/lops/lop-domain-a72-prune.dts
- lopper/lops/lop-domain-linux-a53-prune.dts
system device-tree generator tool is now generating the R5 cores as individual cpu cluster nodes, update the lops file for the same.
> lopper: lops: Remove R5 cpu nodes while generating linux dtb

- lopper/assists/baremetal_xparameters_xlnx.py
While generate c defines don't geneate define with - it should be generated with _ between name spaces.
> lopper: assists: baremetal_xparameters_xlnx: Fix whitespace after the macro name warning

- lopper/lops/lop-domain-a72-prune.dts
Somehow device tree style comments (//) have appeared in the python code blocks of these lops. That is a syntax error, and makes them invalid.
convert to python style #, to at least make them executable again.
> lops: fix comment style

- lopper/assists/baremetal_xparameters_xlnx.py
Generate CPU timestamp frequency (XPAR_CPU_TIMESTAMP_CLK_FREQ) in xparameters.h file.
> lopper: assists: baremetal_xparameters_xlnx: Generate time stamp frequency define

- lopper/assists/baremetal_bspconfig_xlnx.py
- lopper/assists/baremetal_gentestapp_xlnx.py
- lopper/assists/baremetal_getsupported_comp_xlnx.py
- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/baremetalconfig_xlnx.py
- lopper/assists/baremetaldrvlist_xlnx.py
- lopper/assists/baremetallinker_xlnx.py
- lopper/assists/bmcmake_metadata_xlnx.py
- lopper/assists/common_utils.py
Currently, the baremetal assists are taking ESW repo as an input to determine the required drivers/libs/apps yaml paths. This limits these assists to be used only with one repo input. This patch enables the usage of multiple esw repo paths, maintaining the one repo feature as is.
Signed-off-by: Onkar Harsh <onkar.harsh@amd.com>
> baremetal_assists: Modifying baremetal assists to support use of multiple ESW repos

- lopper/lops/lop-domain-linux-a53-prune.dts
All the memory ranges mentioned in a memory node may not be valid for a given cpu cluster, update the memory node as per cpu cluster mapping.
> lopper: lops: lop-domain-linux-a53-prune: Update memory nodes as per cpu cluster mapping

- lopper/assists/bmcmake_metadata_xlnx.py
Generate the lwip meta-data(xtopology_g.c) for lwip library by reading the type instead of using hardcoded library name(lwip211).
> lopper: assists: bmcmake_metadata_xlnx: Don't use hardcoded library name

- lopper/assists/baremetallinker_xlnx.py
When performing arithmetic operations on hexadecimal strings, convert the value into integer and perform arithmetic operations.
> lopper: assists: baremetallinker_xlnx: Fix compare logic in hex strings

- lopper/assists/bmcmake_metadata_xlnx.py
Remove unneeded list set operations on node list becasue of this line nodes names are coming out of order in cmake meta-data.
> lopper: assists: bmcmake_metadata_xlnx: Remove unneeded list set operation on node list

- lopper/assists/baremetal_xparameters_xlnx.py
Added support for generating the NUMBER_OF_SLRS define if the slrcount variable defined in the root node.
> lopper: assists: baremetal_xparameters_xlnx: Add support for generating NUMBER_OF_SLRS define

- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/baremetaldrvlist_xlnx.py
- lopper/assists/bmcmake_metadata_xlnx.py
1. Update the assists to handle drivers which are part of system device-tree folder.
2. Update the ip_dict to use xlnx,name property instead of xlnx,ip-name
to provide all the hardware instances in the ip_drv_map.yaml file
> lopper: xilinx baremetal assist updates

- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/baremetalconfig_xlnx.py
In the driver config structure this property is of type struct to avoid Missing braces around initializer warning add braces around value (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119 )
> lopper: assists: baremetalconfig_xlnx: Special handling for Handler-table property

- lopper/assists/openamp_xlnx.py
Ensure that if the dtsi included is using the board number, this is also supported.
- For ZynqMP enable zcu102
- For Versal enable vck190
>  openamp: xlnx: Update compatible string checks

- lopper/lops/lop-domain-linux-a53-prune.dts
After pruning the system device-tree for linux need to prune symbol node as well so that it will be in sync with the generated linux device-tree nodes, updated the logic for the same.
> lopper: lops: lop-domain-linux-a53-prune: prune symbol node

- lopper/assists/baremetalconfig_xlnx.py
- lopper/assists/common_utils.py
Currently we are relying on the Config sturcture name to get the _g.c file name. Instead we can rely on the _g.c file name already present in the driver folder and create the _g.c file with the same name as the output of this assist. This solves the issue with devcfg driver where the Config name is DCfg but the driver name and the file name starts with devcfg
> bmconfig: Change in the logic to get the _g.c name for the drivers

- lopper/assists/baremetallinker_xlnx.py
- lopper/lops/lop-microblaze.dts
- Update assist file baremetallinker_xlnx to support mig7 memory in linker
file generation
- Add lop-microblaze.dts lops file to generate compiler
flags and library path for Microblaze processor.
Microblaze compiler flags are tightly coupled with
Microblaze processor configured in specific HW design.
lop-microblaze.dts generates cflags.yaml based on CPU node
properties, which contains compiler flags and standard library path.
> lopper: Add initial PL Microblaze support

- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/bmcmake_metadata_xlnx.py
If device_id and slrcount variable present in the root node generate the value of these properites in the cmake meta-data couple of secure libraries needs this information. Generate device_id param in the xparameters.h file.
> lopper: assists: Generate device_id and slrcount information in the cmake meta-data

- lopper/assists/baremetal_xparameters_xlnx.py
Update the logic to generate the XPAR_PSU_PSS_REF_CLK_FREQ_HZ define for all the processors if the xlnx,pss-ref-clk-freq property is present in the cpu node.
> lopper: assists: baremetal_xparameters_xlnx: Generate PSS_REF_CLK define for all the processors

- lopper/assists/bmcmake_metadata_xlnx.py
Have proper checks to avoid the index out of range error i.e IndexError.
> lopper: assists: bmcmake_metadata_xlnx: Fix race condition in the assist

- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/bmcmake_metadata_xlnx.py
lwip library topology index is currently being generated based on the driver probe order which may vary based on the repo order fix is by updating the index based on the driver name.
> lopper: assists: bmcmake_metadata_xlnx: Fix the lwip topology index

- lopper/assists/baremetal_gentestapp_xlnx.py
- lopper/assists/baremetal_getsupported_comp_xlnx.py
- lopper/assists/baremetalconfig_xlnx.py
Make sure node order is preserved.
> lopper: assists: baremetalconfig_xlnx: Make sure node order is preserved

- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/bmcmake_metadata_xlnx.py
If board variable is present in the root node generate the value of this property in the cmake meta-data and in xparameters.h file
> lopper: assists: Generate board information in the cmake meta-data

- lopper/lops/lop-microblaze.dts
- Add handling for xlnx,data-size to support 64 bit Microblaze processor
- Fix specific Microblaze HW designs where FPU is enabled
> lops: lop-microblaze: Fix generated library path

- lopper/lops/lop-microblaze.dts
For few HW designs "model" property might not be populated
in system device tree. If so, code which reads model
property throws exception.
Add checks in lops, so that model property value would
be read only when it is present in processor node.
> lops: lop-microblaze.dts: Add check for model property

- lopper/assists/baremetal_gentestapp_xlnx.py
If the driver folder name is versioned current logic is reading incorrect yaml file, this commit fixes the same.
> lopper: assists: baremetal_gentestapp_xlnx: Update the assist to handle versioned drivers

- lopper/assists/baremetal_xparameters_xlnx.py
Fix the IndexError in the assist by updating the proper checks in the code.
> lopper: assists: baremetal_xparameters_xlnx: Fix IndexError in assist

- lopper/assists/bmcmake_metadata_xlnx.py
Generate CMAKE_MACHINE variable for microblaze processor if xlnx,family property is present.
> lopper: assists: bmcmake_metadata_xlnx: Generate CMAKE_MACHINE variable for microblaze processor

- lopper/assists/baremetallinker_xlnx.py
1. If the app template has linker_constraints i.e heap and stack size configuration generate the same in cmake meta-data.
2. Update the tcm memory node checks for all the processor instances
> lopper: assists: baremetallinker_xlnx: linker updates

- lopper/assists/baremetallinker_xlnx.py
Commit 64f6ad5e9cf8 (lopper: assists: baremetallinker_xlnx: Fix race condition in the memtest config) is not handling the has_ocm variable properly due to which getting the Fix UnboundLocalError has_ocm, this commit fixes the same.
> lopper: assists: baremetallinker_xlnx: Fix UnboundLocalError has_ocm

- lopper/assists/baremetalconfig_xlnx.py
By default, reg and ranges are the only 64 address properties which have specific handling in the baremetal config assist. For PCIE, there is a requirement to read two 32 bit cells of hex values as a 64 bit address and not a list of two different hex values. This value can be different than the existing reg property. Thus, an additional usage of padding is being introduced here to support treating multiple cells of hex values as one big address on demand.
> lopper:assists:baremetalconfig : Adding support to read a 64 bit property from a node on demand

- lopper/assists/baremetal_xparameters_xlnx.py
The subnodes within a device (where they exist) are not necessary to be included in xparamaters.h, the base paramaters are sufficeint.
This patch excudes the submodes by using a break on finding a dict withing the node being parsed.
"nosub" is also a command that should not be included, a continue is used for this instance.
> lopper: assists: baremetal_xparameters_xlnx: Ignore Subnodes

- lopper/assists/baremetal_xparameters_xlnx.py
c4c0b126fc8f5b commit added support to get a 64 bit property in xparameters.h. While adding the support, the "index" variable was wrongly used as a loop variable. The "index" variable was already declared before as a top level loop variable and this led to a wrong canonical entry in xparameters file. Renaming this index loop variable to fix this issue.
> assists:baremetal_xparameters_xlnx: Fix for the wrong reuse of variable "index"

- lopper/assists/gen_domain_dts.py
When user provided processor name and system device-tree as input this assist produces as a dts file which contains nodes mapped to that processor instance.
> lopper: assists: gen_domain_dts: Add assist for generating processor specific dts

- lopper/assists/baremetal_gentestapp_xlnx.py
- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/baremetalconfig_xlnx.py
- lopper/assists/baremetaldrvlist_xlnx.py
- lopper/assists/bmcmake_metadata_xlnx.py
- lopper/assists/gen_domain_dts.py
If the system devic-tree is already pruned no need to run the get_mapped_nodes() API update the assist logic for the same.
> lopper: assists: Add support for pruned system device-tree

- lopper/assists/openamp_xlnx.py
- lopper/assists/openamp_xlnx_common.py
Enable multiple channels to be defined in YAML as either:
- 1-1
- 1-many
Also add option where zero-indexed arg can be provided to denote which channel the output header file is targeting. If none provided default to 0.
The option is as follows:
openamp [remote|host]  <channel-ID>
where this is channel ID is expected to be an int value.
> openamp: xlnx: Enable multiple channels in YAML

- lopper/assists/openamp_xlnx.py
Previously False was considered same as 0 so use isinstance instead of not keyword to compare to int
> openamp: xlnx: Update channel check to account for 0

- lopper/assists/baremetalconfig_xlnx.py
- lopper/assists/xlnx_overlay_dt.py
Existing logic is generating empty config file in case driver
is not compatible with the given sdt, ideally we shouldn't
generate the config file
> Don't generate  config file in case driver is compatible with the given sdt

- lopper/lops/lop-domain-a72-prune.dts
1. Don't delete the pl reference nodes from the final dts/dtb file these nodes are expected by the linux driver
2. Prune the symbol node
> lop-domain-a72-prunce.dts bug fixes

- lopper/assists/baremetal_xparameters_xlnx.py
Macros which are of type string in xparameters.h are missing "" around them. Such macros can't be used in C code. Wrap all the string macros within "".
> assists:baremetal_xparameters_xlnx: Correct the string macros in xparameters

- lopper/lops/lop-domain-a72-prune.dts
- lopper/lops/lop-domain-linux-a53-prune.dts
Make sure to keep the status disabled nodes in the pruned tree as they are essential for Xen.
> lopper: lops: Keep the status disabled nodes in the pruned tree

- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/bmcmake_metadata_xlnx.py
Update the assists to have a proper checks inorder to avoid Python NameError, variable 'not defined'.
> lopper: assists: baremetal*: Add proper checks

- lopper/assists/baremetallinker_xlnx.py
- lopper/lops/lop-microblaze-riscv.dts
This pull request does following,
Adds lops file to generate Microblaze RISC-V compiler flags.
Microblaze RISC-V compiler flags are tightly coupled with
Microblaze RISC-V processor configured in specific HW design. lop-microblaze-riscv.dts generates cflags.yaml based on CPU
node properties, which contains compiler flags, part of linker flags dependent on HW and standard library path.
Fixes handling for lmb bram
Existing logic assumes that LMB BRAM is always mapped at 0x0. It is incorrect, it can be mapped
anywhere within processor address map.
Also, initial 80 bytes of LMB BRAM would be used directly by vector sections in linker script, only
in case of classic Microblaze processor. Hence, addition of 80 bytes offset to LMB BRAM should be done only in case
of Microblaze case.
This bug was …
> lopper: Add support for Microblaze RISC-V baremetal BSP

- lopper/assists/baremetal_bspconfig_xlnx.py
- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/baremetallinker_xlnx.py
Presently, the NOC address related macros come in a generic way. To inline with the existing macro names and make the existing Translation Table work, improvise the logic to add region names of all the possible regions for AXI_NOC and AXI_NOC2.
> lopper:assists:baremetal_xparams Generate the Memory region names within NOC macros

- lopper/assists/baremetalconfig_xlnx.py
Correct the PCI range mapping when the leading zeroes are removed from the lower address nibbles.
Sample range example: <0x43000000 0x80 0x0 0x80 0x0 0x0 0x80000000>
expected entry in config structure: 0x8000000000 0x807FFFFFFF
> lopper:assists:baremetal_config: Correct the pci range mapping

- lopper/assists/openamp_xlnx.py
Ensure that IPI Message buffer values is proper.
There was bug in that the values were switched
> openamp: xlnx: Update RPMsg kernel mailbox output

- lopper/assists/bmcmake_metadata_xlnx.py
interrupt property is optional property for all peripheral devices. It is fair scenario to not to have interrupt property in specific device node.
bmcmake_metadata_xlnx assist assumes that each timer device always contains interrupt property. It is trying to get interrupt property details without confirming whether property is present in given node.
Update assist file to check for presence of interrupt property before accessing it to avoid BSP creation failure.
Note: This bug found while testing ZU+ HW design, where AXI timer is present in PL and interrupt for AXI Timer IP is not enabled.
> assists: bmcmake_metadata_xlnx: Add check for interrupt property

- lopper/assists/xlnx_overlay_dt.py
For overlay use cases, this patch adds fpga-PR* child nodes to the fpga node to handle the fpga partial configuration use cases.
> xlnx_overlay_dt.py: Update script to support partial use cases

- lopper/assists/baremetalconfig_xlnx.py
In cases where there are serial nodes in the SDT but none of them are mapped to the processor being targeted in the BSP, the assist should avoid generating STDIN and STDOUT macros. Presently, it is raising an exception that "'name' is not found for the serial_node". Fix the same by checking if the serial_node exists before the 'name' comparison happens with the other nodes.
> assists:baremetalconfig: Avoid the error when there is no serial mapped to the processor

- lopper/assists/baremetal_xparameters_xlnx.py
Interrupt IDs for PS peripherals are already part of xparameters_ps.h in embeddedsw source so don't generate interrupts ID for PS peripherals in xparameters.h
> lopper: assists: baremetal_xparams: Done generate interruptIDs for PS peripherals

- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/baremetalconfig_xlnx.py
Device Tree doesn't allow a floating point number in it as is. This is leading to complexity in the baremetal use case as we have one to one mapping of data types between the device tree entries and the baremetal xparameters/config structures. Therefore, provide a flexibility to pass the floating number in device tree as a string. Add intelligence in the assist to deduce a floating number within string.
> lopper: assists: baremetal*: Add provision to pass float numbers from SDT as is

- lopper/lops/lop-microblaze-riscv.dts
Existing logic for use-muldiv fails for HW designs where use-muldiv is set to 2. In such desgns "m" would not be added to compiler flags, it results into generation of invalid compiler flags.
Also, existing logic is not considering use-fpu property value while setting abi flags.  It results into incorrect abi flags for HW designs where use_fpu is set to 1 or 2.
This patch fixes issues explained above.
> lops: lop-microblaze-riscv: Fix handling of use-muldiv and use-fpu

- setup.py
commit 738df8cc6819 (yaml: support ruamel versions > 0.17.x) added support to check the ruamel version before employing the yaml specific APIs. While doing so, packaging module was imported but it was never invoked. Moreover, if at all it had to be used, it should have been updated under the requirements in setup.py. This statement is leading to missing packaging module related errors as packaging doesnt come with all python versions by default.
Remove this unused import statement of packaging module.
> yaml: Remove the unused import of "packaging" module

- lopper/assists/xlnx_overlay_dt.py
In a given system device-tree it can have same node name under multiple buses use the label name instead of node name for getting the proper interrupt parent node.
> lopper: assists: xlnx_overlay_dt: Fix wrong gic_node referencing

- lopper/assists/baremetalconfig_xlnx.py
- lopper/assists/baremetallinker_xlnx.py
- lopper/assists/gen_domain_dts.py
- lopper/lops/lop-domain-linux-a53-prune.dts
There is often a use case to construct a 64-bit value from 2 32-bit cells in a device tree. Presently, ljust is being used to convert the lower cell value into a valid 32-bit number. Use of ljust for this is not taking the leading zeroes into account. It is appending 0s always at the end which means 0x927 and 0x9270000 entries of device tree becomes the same after processing. Fix this by replacing ljust with string formating to 32 bit values (:08x).
> lopper:assists:baremetal*: Correct the steps to construct a 64 bit value from 2 32-bit cells

- lopper/assists/gen_domain_dts.py
- lopper/assists/xlnx,xdma-host.yaml
In the system device-tree generated xdma node there are lot of properties getting generated in the node, due to which linux dtb generation is failing due to size limiation. Fix this issue by reading the Linux driver yaml binding doc and keep only those properties in the node.
Note: This is workaround, We are planning to read the yamls from the Linux sources instead of copying it to assists folder it's TODO.
> lopper: assists: Add special handling for xdma pcie

- lopper/assists/baremetal_gentestapp_xlnx.py
- lopper/assists/baremetal_getsupported_comp_xlnx.py
- lopper/assists/baremetalconfig_xlnx.py
- lopper/assists/baremetaldrvlist_xlnx.py
- lopper/assists/bmcmake_metadata_xlnx.py
To get the driver name of the version driver we are using re.sub with v_* string there can be driver with v_* name example (v_vcresampler) for such drivers existing code is returning wron driver name fix this issue by using re.split().
> lopper: assists: barmetal*: Fix race condition in the version driver handling

- lopper/assists/gen_domain_dts.py
As there are 2 of each TCM bank in the input SDT, prune the global TCM node for each register space.
> lopper: assists: gen_domain_dts: Remove dupe TCM node

- lopper/assists/baremetallinker_xlnx.py
538f6b5c7171 commit (assists: baremetallinker: Correct the start address for text and data sections for microblaze) added the logic to start the BRAM or the DDR addresses from 0x50 for all the Microblaze designs. While doing so, the logic to check for the start address condition was missed. If the memory is not falling under first 0x50 bytes which is reserved for reset vectors, there is no need of this manipulation. Fix the same.
> assists:baremetallinker: Correct the logic to set the start address of linker section for microblaze

- lopper/assists/baremetal_validate_comp_xlnx.py
- lopper/assists/bmcmake_metadata_xlnx.py
For emacps driver phy-handle property is optional for some configurations, update the checks for the same.
> lopper: assists: baremetal_validate_comp_xlnx: Add special handling for emacps

- lopper/lops/lop-microblaze-riscv.dts
Include bit manipulation extensions zba, zbb, zbc, and zbs in archflags, 
if said extensions are enabled in given HW design.
> lops: lop-microblaze-riscv: Add support for bit-manipulation extensions

- lopper/assists/gen_domain_dts.py
- lopper/assists/xlnx,clocking-wizard.yaml
Prune the clocking wizard node to remove unused params.
The zcu216 bsps are failing because the dt is not fitting in the quater of 500K allocated.
So lets remove the unused parameters from the dt.
> lopper: assists: gen_domain_dts: Prune clocking wizard

- lopper/assists/gen_domain_dts.py
ddr4 is a mig series memory IP. Remove the PL DDRs from default linux device trees. With these present, a kernel crash is observed This needs to be revisited while adding linux support for Soft Microblaze.
> assists:gen_domain_dts.py: Remove PL DDR from default linux device tree

- lopper/lops/lop-microblaze-riscv.dts
For MB V HW designs, 16 combinations of architecture dependent flags are possible(m, a, f, c). Based on parameters enabled in HW design, corresponding GNU library needs to be used during linking.
As of now, in Vitis installation, only 7 combinations of 32 bit libraries are present (rv32i, rv32im, rv32iac, rv32imac, rv32imc, rv32imafc, rv32imafdc). If library corresponding to configuration used in specific MB V design is not present in Vitis installation, ideally library nearest to given HW configuration should be used.
For now, update logic to support fallback mechanism for rv32ic, rv32ia and rv32ima libraries, in future support would be extended to other libraries as well.
> lops: lop-microblaze-riscv: Add support for library fallback mechanism

- lopper/assists/baremetal_xparameters_xlnx.py
Update assist to export following #defines to xparameters.h
XPAR_MICROBLAZE_RISCV_USE_FPU
XPAR_MICROBLAZE_RISCV_USE_MMU
XPAR_MICROBLAZE_RISCV_USE_SLEEP
XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT
XPAR_MICROBLAZE_RISCV_D_LMB
XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE
XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE
> assists: baremetal_xparameters_xlnx: Export defines needed by MB V BSP

- lopper/assists/baremetallinker_xlnx.py
- lopper/assists/gen_domain_dts.py
assists: gen_domain_dts: Remove BRAM memory nodes from linux device tree
As an extension of this commit 8476601a9fb1 (assists:gen_domain_dts.py: Remove
PL DDR from default linux device tree), add bram IP into the list of PL memory
IPs that need to be removed.
assists: linker/domain: Add support for linear flash memories in linker script
Memory segments from Linear flash IPs like axi_emc, psu_qspi_linear and ps7_qspi_linear
can also be used in linker script. At the same time, these memory nodes have to be
removed from the linux device tree. Add the support for these two use cases.
> Support for linear flash IPs in linker/ Removal of BRAM from linux DT

- lopper/assists/baremetal_validate_comp_xlnx.py
- lopper/assists/baremetal_xparameters_xlnx.py
--> Generate baseaddress and interrupt defines for all possible ranges
--> Update mem_type check for microblaze_riscv
-->  Update the barmetal validate assist to handle use cases where
dev_type is missing in the driver yaml.
> Baremetal assist bug fixes

- lopper/assists/gen_domain_dts.py
- lopper/lops/lop-gen_domain_dts-invoke.dts
Add option that if present allows user to prune TCM DT nodes.
To remove TCM nodes, add third option on command line for this assist.
> lopper: assists: gen_domain_dts: Add option to prune TCM nodes

- lopper/base.py
resets and assigned-clocks are generic property that contains phandles and fields. We add it to our base configuration so lopper can do phandle symbolic replacement during output processing.
> base/phandle: add resets and assigned-clocks

- lopper/base.py
To full handle the clock-cells property as defined in the clock dts binding:
https://github.com/devicetree-org/dt-schema/blob/main/dtschema/schemas/clock/clock.yaml
We must adjust our phandle map to not only specify the field to look up, but also allow an expression to indicate how many fields the looked up value should skip.
In the case of clock. A found value of '0' means that there are no clock inputs, and the next field should be looked at. A found value of '1' means that there's an input specified so the next phandle field will be in '2'
This is a different behaviour from address cells, so to keep things generic we specify a +1 expression to be evaluated against the found value.
> base: add expression to clock phandle description

- lopper/assists/xlnx,rfdc.yaml
The "num-insts" device tree property should not be pruned for rfdc nodes.
Adding this property to the xlnx,rfdc.yaml wil remedy this.
> lopper: assists: Add num-insts to rfdc node

- lopper/lops/lop-microblaze-riscv.dts
GNU libraries in 2024.1 Vitis installations are changed. Few library directories are removed, and few are renamed. Update MB V lops file to be in sync with Vitis GNU riscv library installation.
Also, remove libraries which are having 1:1 mapping from archflags_lib_map dictionary, keep only libraries for which fallback is needed OR library directory name is different than corresponding arch flags.
> lops: lop-microblaze-riscv: Sync with Vitis riscv gnu lib installation

- lopper/assists/bmcmake_metadata_xlnx.py
Update the assists to have a proper checks inorder to avoid Python KeyError failed to read axistream-connected property.
> lopper: assists: bmcmake_metadata_xlnx: Add proper checks

- lopper/assists/baremetallinker_xlnx.py
There are Versal HBM series SoCs that integrates the most advanced HBM2e DRAM, providing high memory bandwidth and capacity within a single device. AXI_NOC1 IP inside these SoCs have HBM specific address blocks alongside the regular DDR specific ones. Add support for generating macros in xparameters.h and respective entries inside linker script for these HBM blocks.
> assists: baremetallinker: Add HBM specific address ranges in axi_noc1 dictionary

- lopper/assists/baremetallinker_xlnx.py
This commit addresses a build failure in the `memory_test` application on the ZC706 board with the preset DMA design. The issue arises from the incorrect inclusion of non-RAM memories in the linker script, which causes insufficient memory during the build process.
To resolve this, the logic is updated to only include RAM memories (`ps7_ram_0` and `ps7_ram_1`) by modifying the condition to match '_ram' in the memory names. This ensures that only the appropriate memory regions are assigned, preventing the build failure.
Additionally, support is added for the memory test application for MicroBlaze designs.
> assists: linker_xlnx: Fix memory assignment to avoid build failure

- lopper/lops/lop-ttc-split.dts
TTC IP in the ZynqMP and Versal has 3 counters, Baremetal ttc driver expects each counter as a separate driver but in SDT flow as per spec we have a single node for one IP, Add support for new additional nodes as per ttc BareMetal driver requirements.
> lopper: lops: lop-ttc-split.dts: Add new lops file for baremetal ttc driver

- lopper/assists/yaml_bindings/xlnx,csi2rxss.yaml
- lopper/assists/yaml_bindings/xlnx,dsi.yaml
- lopper/assists/yaml_bindings/xlnx,frmbuf-rd-wr.yaml
- lopper/assists/yaml_bindings/xlnx,v-demosaic.yaml
- lopper/assists/yaml_bindings/xlnx,v-gamma-lut.yaml
- lopper/assists/yaml_bindings/xlnx,v-vpss-csc.yaml
- lopper/assists/yaml_bindings/xlnx,v-vpss-scaler.yaml
Add following list of yaml documentation to support MIPI linux solution:
1. MIPI CSI2 RX SS
2. MIPI DSI TX SS
3. Demosaic
4. Gamma Lut
5. VPSS CSC and Scaler
6. Framebuffer RD/WR
> lopper: assists: gen_domain_dts: Add mipi pipeline documentation

- lopper/assists/baremetallinker_xlnx.py
The current logic to find phandle in address map is actually checking against all fields in addressmap(address, size, phandle) which is incorrect. Fix this by checking it only against the phandle in addressmap.
> assists: baremetallinker: Update the logic to find phandle in addressmap

- lopper/assists/baremetallinker_xlnx.py
For memory tests, the default_ddr is always getting assigned to zeroth bram even when we have multiple brams in the design. Ideally, it is expected to be assigned to bram with higher size, update the logic accrodingly.
> assists: baremetallinker: Fix ddr_default logic for memory tests

- lopper/assists/zuplus_xppu_default.py
When I was packaging lopper, I got the following error:
```python
*** Error compiling '.../lib/python3.12/site-packages/lopper/assists/zuplus_xppu_default.py'...
File ".../lib/python3.12/site-packages/lopper/assists/zuplus_xppu_default.py", line 96
elif:
^
SyntaxError: invalid syntax
*** Error compiling '.../lib/python3.12/site-packages/lopper/assists/zuplus_xppu_default.py'...
File ".../lib/python3.12/site-packages/lopper/assists/zuplus_xppu_default.py", line 96
elif:
^
SyntaxError: invalid syntax
```
> assists: zuplus_xppu_default: fix syntax error

- lopper/assists/baremetal_bspconfig_xlnx.py
- lopper/assists/baremetal_gentestapp_xlnx.py
- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/lops/lop-ttc-split.dts
Pull request does the below
lopper: assists: baremetal_bspconfig_xlnx: Add support for generating microblaze_exceptions_g.h header
lopper: assists: baremetal_gentestapp_xlnx: Fix race condition while making the Interrupt Controller example as the primary example
lopper: assists: baremetal_gentestapp_xlnx: Add support for override stdin configuration
lopper: assists: baremetal_xparameters_xlnx: remove references to duplicate SDT* defines
lopper: lops: lop-ttc-split: Rename the label names to inline with old tool
> lopper: Enhancements in BareMetal flow

- lopper/assists/baremetallinker_xlnx.py
From Versal Gen2 platform onwards, the NAME and IP_NAME will not have any prefixes. Add the support for the same. APU TCM support is yet to be added.
> assists: baremetallinker: Add support for the memory sections with new taxonomy changes

- lopper/__init__.py
- lopper/base.py
When LOPPER_CPP is set to other C preprocessors, e.g. aarch64-none-elf-cpp in a cross compilation environment, lopper still checks the existence of `cpp` and refuses to run if not exists.
Also fixed lopper passing an unrecognized argument `--passthru-comments` when LOPPER_CPP is set to C processors other than `pcpp`.
> lopper: don't check the existence of cpp when LOPPER_CPP is set

- lopper/assists/gen_domain_dts.py
Few memory IPs and peripheral IPs are not needed in Linux device tree. Add them in the linux ignore list to delete such nodes from device tree.
> assists: gen_domain_dts: Add few Zynq specific IPs in Linux ignore list

- lopper/lops/lop-microblaze-riscv.dts
ASU is a RISC-V processor and it also requires the RISC-V specific lops operations to set the compiler flags. Modify the node selection operation in the lops file to add support for the same.
> lops: mb-riscv: Add generic cpus_* pattern to re-use riscv lop file for asu

- lopper/lops/lop-microblaze-riscv.dts
Updating multilib mappings based on multilib libraries installed in vitis 2024.2 version.
Also, include mappings for 64 bit variant.
> lops: lop-microblaze-riscv: Update multilib mappings

- lopper/lops/lop-cpu-oslist.dts
Add a new lops file that can generate ai_engine as a cpu. Update the earlier cpulist.yaml with supported os data as well.
> lops:lop-cpu-oslist Add a new lops file to get ai_engine as cpu

- lopper/assists/bmcmake_metadata_xlnx.py
In windows paths was refered using \ slash instead of / slash, Update the example path for the same in case of windows OS.
> lopper: assists: bmcmake_metadata_xlnx: Update the driver example meta-data to take care of windows platform as well

- lopper/assists/gen_domain_dts.py
- lopper/assists/xlnx_overlay_dt.py
lopper: assist: gen_domain_dts: Update the linux device-tree to delete unneeded nodes
lopper: assists: xlnx_overlay_dt: Improvments in the assist
Update the assist for the below use cases
--> Don't generate pl.dtsi in case of no amba_pl node in the system
device-tree
--> Add support for passing processor name as input instead of hardcoded
machine name.
> Bug fixes in Linux device-tree generation

- lopper/assists/baremetallinker_xlnx.py
axi_emc is a softIP used to interface with external memory devices. The block provides memory controller functionality primarily for parallel NOR Flash and linear flash devices. ELFs can't be directly downloaded over axi_emc using "dow" and a separate flash utility is needed. Therefore, avoid setting axi_emc as the default memory in all the linker sections. This is a makeshift solution until all the data and code sections are properly divided among the available memory IPs.
> assists:baremetallinker: Avoid setting axi_emc as the default memory in linker sections

- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/baremetalconfig_xlnx.py
For Zynq Nand controller the baseaddress of the IP is part of the ranges property instead of reg property updated the assits to handle this use case.
> lopper: assists: Add special handling for zynq nand

- lopper/assists/gen_domain_dts.py
Some designs can have cpu_ as prefix in IPs names (sdt labels).
cpunode_list = sdt.tree.nodes('/cpu.@.')
was employed in gen_domain_dts assist to get all the cpu nodes from SDT and delete the cpu nodes (available in the root node) that are not supposed to be in that domain. In this case, the logic deleted all the IP nodes under axi bus starting with cpu_ as sdt.tree.nodes() does regex matching by default.
Employ the strict check (that was introduced a couple of weeks back in Lopper) to avoid the same.
> assists: gen_domain_dts: Add strict check while fetching cpu nodes from SDT

- lopper/assists/baremetal_gentestapp_xlnx.py
Update the conditional check from 'XAxiEthernet' to 'AxiEthernetSgDmaIntrExample' to enhance testapp selection logic.
> lopper: assists: baremetal_gentestapp_xlnx: Improve test app selection logic

- lopper/assists/gen_domain_dts.py
After commit 0551671 the TCM nodes were still deleted. Add check to preserve TCM nodes.
> lopper: assists: gen_domain_dts: Preserve TCM nodes with latest checks

- lopper/assists/yaml_bindings/xlnx,vphy.yaml
Commit 6515708cf697 (lopper: vphy: Add FMC connector property) had a copy paste error while adding the entry in the dt-binding YAML. Fix the YAML syntax error in the same.
> lopper: assist: dt-binding: vphy: Fix the syntax error in vphy YAML binding

- lopper/assists/yaml_bindings/xlnx,v-dprxss.yaml
- lopper/assists/yaml_bindings/xlnx,v-hdmi-rx-ss.yaml
- lopper/assists/yaml_bindings/xlnx,v-hdmi-rxss1.yaml
- lopper/assists/yaml_bindings/xlnx,v-hdmi-tx-ss.yaml
- lopper/assists/yaml_bindings/xlnx,v-hdmi-txss1.yaml
Add HDCP1x keymanagement property for DP and HDMI subsystems.
> lopper: hdmi: Add HDCP1x Keymanagement property

- lopper/assists/gen_domain_dts.py
- lopper/assists/zephyr_supported_comp.yaml
Zephyr OS has strict device-tree node checking and property checking currently it support only timer, interrupt controller and uartlite IP's only for any given MB-V design keep only those nodes and update memory node and cpu node and alias nodes as per zephyr dts specificaion.
FIXME: file zephyr_supported_comp.yaml was added for the timebeing proper fix would be reading the yaml specification from zephyr binding docs.
> lopper: assists: gen_domain_dts: delete unneeded nodes for zephyr MB-V

- lopper/assists/gen_domain_dts.py
- lopper/base.py
- lopper/lops/lop-mbv-zephyr-intc.dts
zephyr-amd repository has been updated with zephyr upstream
version 3.7. It has few changes related to Kconfig files,
kcofigs  related to HW extensions are moved from soc/mbv32/kconfig.soc
to soc/mbv32/Kconfig. Also, interrupt controller wiring is modified.
> Align generated Kconfig files and device tree for mbv32 zephyr with zephyr-amd repository

- lopper/assists/baremetal_gentestapp_xlnx.py
- lopper/assists/common_utils.py
lopper: assists: common_utils: Add support for read-only embeddedsw usecase
lopper: assists: baremetal_gentestapp_xlnx: Exclude pulling uartlite examples for tmr-sem
> Bug fixes in the peripheral test app

- lopper/assists/gen_domain_dts.py
IP Names have been updated from Versal Gen2 family onwards. There will no longer be any psu/psv/psx suffixes in the IP Names for Versal Gen2 family. Add Versal Gen2 specific IP Name entries in the ignore list to avoid un-needed IPs in linux domain and keep the linux domain device tree size in check.
> lopper: assists: gen_domain_dts: Add Ignore IP entries for Versal Gen2 linux domain

- lopper/__init__.py
The PurePosixPath was causing problems in the Windows flow since it is a supported method for Linux.
Change the logic from "PurePosixPath( output_filename ).is_absolute()" to "os.path.isabs( output_filename )" to support both Windows and Linux flows.
> lopper : Fixed path issues

- lopper/assists/gen_domain_dts.py
Ideally memory node with largest memory size supposed to be pointed to zephyr,sram property. This is not happening with existing implementation. Also, for specific HW designs, assist called with zephyr_dt argument is resulting into errors.
Move memory nodes modifications after setting up zephyr,sram property to fix said issues.
> assists: gen_domain_dts: Fix zephyr,sram property generation

- lopper/assists/bmcmake_metadata_xlnx.py
This reverts commit 742ad54db50969991615af93f9c67e10083b77dd. as this patch needs some more modifications and it was send along with lops patch
> Revert "lopper: assists: Optimized metadeta generation logic"

- lopper/assists/gen_domain_dts.py
- lopper/assists/zephyr_supported_comp.yaml
This pull request updates the Zephyr support in the Lopper project to include additional UART and AXI-IIC node support in the DTS generation.
- Updated the `zephyr_supported_comp.yaml` file to add UART and AXI-IIC components.
- Extended the Zephyr DTS generation script to support:
- `UARTNS550`
- `UARTPS`
- `UARTPSV`
- `AXI-IIC` nodes.
Ajay Neeli <ajay.neeli@amd.com>
> lopper: assists: gen_domain_dts: Add UART and AXI-IIC nodes for Zephyr

- lopper/assists/gen_domain_dts.py
- lopper/assists/openamp.py
- lopper/assists/openamp_xlnx.py
- lopper/assists/openamp_xlnx_common.py
For gen_domain_dts.py plugin, if the openamp domains are present then have this processing occur at the start.
Additionally if the openamp processing ocurred then keep TCM nodes.
For OpenAMP to enable this do the following:
1. If OpenAMP processing occurs then at the end remove the OpenAMP nodes
2. Only output the OpenAMP Configuration header for non-Linux targets
3. Add some OpenAMP lookup tables to aid the gen_domain_dts.py in OpenAMP info lookup
This way the following use cases are still preserved
1. Non-Linux OpenAMP runs
2. If a user keeps the OpenAMP plugin args in a Linux domain Lopper run
> openamp: xlnx: Enable gen_domain to invoke openamp processing

- lopper/assists/bmcmake_metadata_xlnx.py
- lopper/lops/lop-ttc-split.dts
Dynamically added TTC nodes should be excluded from the CMake metadata. a new property, lop-dynamic-ttc-node, has been introduced, and the logic in bmcmake_metadata_xlnx has been updated to ensure these nodes are not included.
> lopper: Add special handling for ttc baremetal use case

- lopper/assists/gen_domain_dts.py
- lopper/assists/zephyr_supported_comp.yaml
Update zephyr_supported_comp.yaml to add AXI GPIO as supported component.
Extended Zephyr DTS generation to support AXI GPIO node.
> lopper: assists: gen_domain_dts: Add AXI GPIO node for Zephyr

- lopper/lops/lop-cpulist.dts
Removed print statements to avoid processors list in command line
> lops: Remove print statement

- README.md
- requirements.txt
Using python3's venv is very powerful and makes doing lopper development and usage easier.
More on it: https://docs.python.org/3/library/venv.html
Update the README to add usage instructions about this and a requirements.txt which makes installing the lopper python dependencies a breeze using pip.
Been using this flow for a while, it'd be a useful addition to lopper mainline so others can also benefit from it.
While at it, fix some minor typos in the README as well.
> lopper: venv: add requirements.txt and venv usage in README

- lopper/assists/openamp_xlnx.py
Only set v2 flag for removing TCM nodes for upstream driver for now
> openamp: xlnx: Update domains removal check

- lopper/assists/baremetalconfig_xlnx.py
This patch adds support for generating the `mdioproducer-baseaddr`
if the `phy-handle` property is absent, default to `0x0` as the base address.
if PHY handle under MAC node,if the parent node has a `reg` property, it is considered a MAC node. Extract the base address from its register.
if PHY handle under MDIO node,if the parent node lacks a `reg` property but its grandparent has one, treat it as an MDIO node and extract the base address from the grandparent.
> lopper: assists: baremetalconfig_xlnx: Add support for 'mdioproducer-baseaddr' property

- lopper/assists/gen_domain_dts.py
- lopper/assists/openamp_xlnx.py
If Gen Domain plugin is invoked for RPU Domain and OpenAMP Conditions are met, then invoke openamp parse routine
Also because there can exist case where the header for OpenAMP Remote is not required, add option to specify no header.
> lopper: assists: gen_domain_dts: Enable RPU domain support for OpenAMP

- lopper/assists/zephyr_supported_comp.yaml
- Add 'current-speed' property to UARTNS550 configuration in zephyr_supported_comp.yaml
> lopper: assists: zephyr: Add current-speed to UARTNS550

- lopper/assists/gen_domain_dts.py
TTC0 is used for RPU scheduler and so in AMP solutions this IP being present can cause issue for such usage.
> lopper: assists: gen_domain_dts: Remove TTC0 for Versal-based SOCs

- lopper/assists/zephyr_supported_comp.yaml
Update zephyr_supported_comp.yaml to add AXI TIMEBASE WATCHDOG as supported component.
Extend Zephyr DTS generation to support AXI TIMEBASE WATCHDOG node.
> lopper: assists: zephyr: Add AXI TIMEBASE WATCHDOG node for Zephyr

- lopper/lops/lop-ttc-split.dts
In case interrupt-parent property exists then only add the interrupts property in the new ttc node.
> lopper: lop: lop-ttc-split: Add check for interrupt parent

- lopper/assists/baremetal_gentestapp_xlnx.py
Updated the baremetal_gentestapp_xlnx.py script to exclude the last TTC instance from peripheral testing for the RPU processor. This is achieved by adding a condition to filter out nodes marked with the lop-dynamic-ttc-node property.
> lopper: Exclude last TTC instance for RPU peripheral tests

- lopper/assists/baremetal_xparameters_xlnx.py
Added a continue statement in the for loop to skip parameters that do not exist in the DT node. This
prevents unnecessary population of non-existent
parameters in xparameters.h
> lopper: Ensure Only Existing DT Node Parameters

- lopper/assists/openamp_xlnx_common.py
Header was invalid after latest commit. fix issue here.
> openamp: xlnx: fix up generated header

- lopper/assists/gen_domain_dts.py
Update linux ignore list to remove mmi_10gne and gty so that these nodes will reflect in corresponding linux device tree.
> gen_domain_dts: update linux ignore list to remove mmi_10gbe and gty

- lopper/assists/baremetalconfig_xlnx.py
Add logic to extract the reg property from subnodes where compatible is "xlnx,gmii-to-rgmii-1.0" and set it as gmiitorgmii-addr. Default to 0 if no match is found.
> baremetalconfig_xlnx : Add support for gmiitorgmii-addr property

- lopper/lops/lop-microblaze-riscv.dts
Add a "b" flag to the architecture flags when the ZBA, ZBB, and ZBS extensions are enabled in the hardware design. If any of these extensions are not enabled, continue using the legacy _zba, _zbb, and _zbs flags.
For now, continue using the legacy libraries to avoid the library mapping logic, as there are only a limited number of "b" extension-enabled libraries available in the Vitis installation.
> lops: lop-microblaze-riscv: Add support for b extension in arch flags

- lopper/assists/gen_domain_dts.py
- lopper/assists/zephyr_supported_comp.yaml
Update assist to support Zephyr compatible DT generation for Cortex-R52 processors present in Versal NET and Versal GEN 2 SoCs.
TODO: Re-use logic to remove un-supported peripheral for MB-V.
> lopper: assists: Add support to generate zephyr compatible DT for R52

- lopper/lops/lop-gic-el1.dts
In the EL1 Non-Secure use case running on top of Xen, a two-level translation table is used, and the GIC address is hardcoded according to Xen mappings, Update the reg property accordingly.
> lopper: lops: lop-gic-el1: Add lops for handling gic e1 ns use case

- lopper/assists/baremetal_gentestapp_xlnx.py
- lopper/lops/lop-ttc-split.dts
- Updated processor check to include cortexr52 for excluding the last TTC instance in Telluride and Palmyre.
- Fixed label handling to correctly split TTC instances.
- Updated copyright for 2025.
> lopper: Fix TTC instance exclusion and DTS split

- lopper/assists/gen_domain_dts.py
Export Kconfigs needed for PMP support.
> assists: gen_domain_dts: Add PMP support for mbv32 zephyr

- lopper/assists/zephyr_supported_comp.yaml
Update zephyr_supported_comp.yaml to add Xilinx WWDT as supported component.
Extend Zephyr DTS generation to support Xilinx WWDT.
> lopper: assists: zephyr: Add Xilinx WWDT node for Zephyr

- lopper/assists/gen_domain_dts.py
Update linux ignore list to remove mmi_gpu so that this node will reflect in corresponding linux device tree.
> gen_domain_dts: update linux ignore list to remove mmi_gpu

- lopper/assists/gen_domain_dts.py
In case of dual channel mode channel 2 node is getting created with property "gpio-controller" as string but this is not inline with zephyr binding as "gpio-controller" should be boolen hence change "gpio-controller" property type from string to boolen.
> lopper: assists: gen_domain_dts: Fix axi gpio DT error

- lopper/assists/gen_domain_dts.py
- lopper/assists/zephyr_supported_comp.yaml
- Updated zephyr_supported_comp.yaml for Cadence I2C
- Extended Zephyr DTS generation to support Cadence I2C node
> lopper: assists: Add Cadence I2C for Zephyr

- lopper/assists/gen_domain_dts.py
commit f67a124128ff("lopper: assists: gen_domain_dts: Add DRC checks for microblaze riscv zephyr handling") added support for drc checks for riscv there are syntax issues in the patch this fixes the same.
> lopper: assists: gen_domain_dts: Fix syntax issues in lopper

- lopper/assists/gen_domain_dts.py
In the Linux device tree, subnodes within the '/amba_pl' node that lack 'reg' and 'ranges' properties have been identified as non-address-mapped. To ensure proper integration and avoid device link failures, these subnodes have been relocated to the root node.
This refactoring improves clarity and maintainability by organizing non-address-mapped components at the root level, aligning with best practices for device tree structure.
> lopper/assists: Move non-address-mapped subnodes from '/amba_pl' to root

- lopper/assists/bmcmake_metadata_xlnx.py
Add a new environment variable SPEED_GRADE in cmake metadata if a property called 'speed_grade' is present in device tree.
> lopper: assists: bmcmake_metadata_xlnx: Add speed_grade property

- lopper/assists/gen_domain_dts.py
Linux supports virtual node as well, meaning the node is not having the base address but it can have its own child nodes and status. There is no register programming done for these nodes, but the driver can rely on them to take care of the platform related programming like enabling clocks, reset, phy config etc.
e.g node:
usb_mmi: mmi-usb {
compatible = "xlnx,versal2-mmi-dwc3";
status = "disabled";
ranges;
#address-cells = <2>;
#size-cells = <2>;
mmi_dwc3: usb@edec0000  {
compatible = "snps,dwc3";
status = "disabled";
reg = <0x0 0xedec0000 0x0 0x10000>;
interrupt-names = "host", "peripheral";
interrupts = <0 191 4>, <0 191 4>;
interrupt-parent = <&imux>;
snps,dis_u2_susphy_quirk;
snps,dis_u3_susphy_quirk;
snps,quirk-frame-length-adjustment = <0x20>;
snps,usb3_lpm_capable;
dr_mode = …
> assists: gen_domain_dts: Keep the nodes having no base address in linux dt

- lopper/assists/openamp_xlnx.py
Remove parsing of openamp-xlnx-native for remoteproc-v2 cases
Allow user to define one core in cluster for single core use in split mode
> openamp: xlnx: updates for latest driver

- lopper/assists/cfg_obj/modules/sdtinfo.py
adding break statement after assignment
Fix overwriting of ipi_bit_pos in each iteration by adding a break after assigning the value. Ensure the correct bit position is set only once for each master and node combination.
> assists: generate_config_object: Fix overwriting of ipi_bit_pos by

- lopper/assists/baremetal_xparameters_xlnx.py
When the 'xlnx,ddrmc5-device-type' property is present in the device tree, define a new macro 'NOC_MC_DDR5' to indicate the presence of the DDRMC5 controller, and generate a specific define for the memory type:
- 'DDRMC5_DEVICE_TYPE_RDIMM' if the device type is RDIMMs
- 'DDRMC5_DEVICE_TYPE_UDIMM' if the device type is UDIMMs
> baremetal_xparameters_xlnx: Add macros DDRMC5 device type

- lopper/assists/baremetallinker_xlnx.py
This fix aligns the address with the expected value used in Classic platform definitions and avoids negative address mapping issues.
> assists: baremetallinker: Add DDR_PL NOC specific address ranges

- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/baremetalconfig_xlnx.py
Updated get_clock_prop to accept an offset parameter, allowing retrieval of specified clocks.
For emacps we need the clock of the tx_clk. The clock returns the tx_clk clock id if found.
Else it returns the first clock in the array.
> lopper: Support specific clock retrieval

- lopper/assists/baremetalconfig_xlnx.py
The clocks property in the device tree consists of tuples in the format: <phandle clock-id>. To correctly extract the clock ID associated with "tx_clk",
the offset needs to account for the two-cell structure.
> lopper: Fix tx_clk index handling in clock property

- lopper/assists/gen_domain_dts.py
- lopper/assists/zephyr_supported_comp.yaml
This change introduces support for generating a zephyr-compatible device tree tailored to the Cortex-A78 from the system-level device tree. It ensures that the A78-specific nodes and properties are correctly extracted and formatted for use in Zephyr builds.
> lopper: assists: gen_domain_dts: Add support for generating cortexA78 specific Zephyr device-tree

- lopper/assists/generate_config_object.py
In generate_gpo_section_data there can be error if trying to access non-existing key in map. Skip lookup if it does not exist.
> assists: generate_config_object: Check key before indexing into map

- lopper/assists/zephyr_supported_comp.yaml
Remove timeout-sec property from WWDT node to sync with upstream DT bindings.
> assists: zephyr_supported_comp: Remove timeout-sec property from wwdt

- lopper/assists/gen_domain_dts.py
- lopper/assists/zephyr_supported_comp.yaml
- Updated zephyr_supported_comp.yaml for AMD-Xilinx IPI Mailbox
- Extended Zephyr DTS generation to support AMD-Xilinx IPI Mailbox node
> lopper: assists: Add AMD-Xilinx IPI for Zephyr

- lopper/assists/openamp_xlnx.py
As YAMLs now only use v2, just use that.
this addresses firmware build issue for linker scripts
> openamp: xlnx: Update mapping to just use v2

- lopper/assists/baremetal_xparameters_xlnx.py
- lopper/assists/yaml_bindings/xlnx,v-hdmi-phy1.yaml
Define a macro to enable or exclude FRL-related logic in the driver, based on the HDMI mode configured in the HDMI 2.1 Rx subsystem IP.
> lopper:assist: Define FRL enable macro based on HDMI mode

- lopper/assists/gen_domain_dts.py
- lopper/assists/yaml_bindings/xlnx,zynqmp-ipi-mailbox.yaml
Add xlnx,zynqmp-ipi-mailbox.yaml to the yaml bindings to prune the additional properties of IPI nodes that are not required for Linux DT.
Add logic to prune IPI child node properties in the Linux DT according to the Yaml Schema by retaining only required properties specified in the Yaml.
> gen_domain_dts: Prune IPI node properties in Linux DT

- lopper/lops/lop-microblaze-riscv.dts
Update the code to use full extension of linkflags without ABI flags to avoid issues with CSRR calls when used with flto flags.
> lops: microblaze-riscv: Use full extension linkflags
